# Generated by Django 2.0.4 on 2018-06-27 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('email_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.CharField(max_length=70)),
                ('email_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dosis',
            fields=[
                ('tipo', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('ci', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=300)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha', models.DateField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('diferencia_horas', models.CharField(max_length=40)),
                ('cantidad_dosis', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('ci_doctor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_doctor', models.CharField(max_length=40)),
                ('apellido_doctor', models.CharField(max_length=40)),
                ('tlf', models.CharField(max_length=40)),
                ('clinica', models.CharField(max_length=40)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('concentracion', models.CharField(max_length=50)),
                ('tipo_dosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Dosis')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('nombre', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuo', models.BooleanField()),
                ('fecha_recipe', models.DateField()),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cita')),
            ],
            options={
                'ordering': ['-fecha_recipe'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoIndicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_indicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Indicacion')),
                ('id_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('ci', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.FloatField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='id_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Tratamiento'),
        ),
        migrations.AddField(
            model_name='medicina',
            name='tipo_medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TipoMedicamento'),
        ),
        migrations.AddField(
            model_name='indicacion',
            name='id_medicina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Medicina'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='email_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='tratamientoindicacion',
            unique_together={('id_tratamiento', 'id_indicacion')},
        ),
        migrations.AlterUniqueTogether(
            name='medicina',
            unique_together={('nombre', 'tipo_dosis', 'concentracion')},
        ),
        migrations.AlterUniqueTogether(
            name='informacion',
            unique_together={('nombre_doctor', 'apellido_doctor')},
        ),
        migrations.AlterUniqueTogether(
            name='imagen',
            unique_together={('id_cita', 'link')},
        ),
    ]
